version: '3'
services:
  db:
    build:
      context: ./SQL
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: patients
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db_2
    ports:
      - "3306:3306"
    tty: true
  app:
    build:
      context: ./restAPI
    volumes:
      - "./../../:/go"
    container_name: golang_app_2
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db