version: '3'
services:
  db:
    build:
      context: ./SQL
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: patients
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
    # command: >
    #   /bin/bash -c "
    #     sleep 5;
    #     nc -lk 0.0.0.0 3306;"

  app:
    build:
      context: ./
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
    links:
      - db
    command: >
      /bin/bash -c "
        sleep 5;
        nc -lk 0.0.0.0 8080;"

  web:
    build:
      context: ./Javascript
    container_name: golang_web
    ports:
      - "8000:80"
    tty: true
    restart: always
    depends_on:
      - app
      - db
    links:
      - app
      - db
    command: ["-c", "./bash_script"]
    # entrypoint: ["/bin/sh"]

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - app
      - db
    command: app:8080 db:3306