// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListPatientsHandlerFunc turns a function with the right signature into a list patients handler
type ListPatientsHandlerFunc func(ListPatientsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListPatientsHandlerFunc) Handle(params ListPatientsParams) middleware.Responder {
	return fn(params)
}

// ListPatientsHandler interface for that can handle valid list patients params
type ListPatientsHandler interface {
	Handle(ListPatientsParams) middleware.Responder
}

// NewListPatients creates a new http.Handler for the list patients operation
func NewListPatients(ctx *middleware.Context, handler ListPatientsHandler) *ListPatients {
	return &ListPatients{Context: ctx, Handler: handler}
}

/*ListPatients swagger:route POST /list listPatients

Lists all patients

Lists all patient_id's, names, genders, and diseases

*/
type ListPatients struct {
	Context *middleware.Context
	Handler ListPatientsHandler
}

func (o *ListPatients) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListPatientsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
