// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PatientList patient list
// swagger:model Patient_List
type PatientList struct {

	// all patients
	AllPatients []*Patient `json:"all_patients"`
}

// Validate validates this patient list
func (m *PatientList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllPatients(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatientList) validateAllPatients(formats strfmt.Registry) error {

	if swag.IsZero(m.AllPatients) { // not required
		return nil
	}

	for i := 0; i < len(m.AllPatients); i++ {
		if swag.IsZero(m.AllPatients[i]) { // not required
			continue
		}

		if m.AllPatients[i] != nil {
			if err := m.AllPatients[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("all_patients" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatientList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatientList) UnmarshalBinary(b []byte) error {
	var res PatientList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
