// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi PatientData
Based on Golang, outputs an array of patients, patient_id, gender, and disease in json


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
