// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Patient patient
// swagger:model Patient
type Patient struct {

	// disease
	Disease *string `json:"disease,omitempty" db:"disease"`

	// gender
	Gender *string `json:"gender,omitempty" db:"gender"`

	// name
	Name *string `json:"name,omitempty" db:"name"`

	// patient id
	PatientID *string `json:"patient_id,omitempty" db:"patient_id"`
}

// Validate validates this patient
func (m *Patient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Patient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Patient) UnmarshalBinary(b []byte) error {
	var res Patient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
